elasticsearchHosts: "https://elasticsearch-master:9200"

elasticsearchUsername: "elastic"
elasticsearchPassword: "edZRURDVIzKwnagm"

protocol: https

service:
  type: NodePort
  port: 5601

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi
